import { supabase } from '@/lib/supabase'
import { PageContent } from '@/lib/pdf-parser'
import { generateEmbedding } from '@/lib/embeddings'
import { log } from 'console'

export async function saveDocument(
  fileName: string, 
  pages: PageContent[], 
  userId: string
) {
  try {
    console.log("Step 1: Creating Chat Session...")
    
    // 1. Insert into 'Chat' (The Parent)
    const { data: chatData, error: chatError } = await supabase
      .from('chats') // <--- Your Table Name
      .insert({
        user_id: userId,
        title: fileName, // We use filename as the initial title
        file_name: fileName,
        // created_at is auto-generated by Supabase
      })
      .select()
      .single()

    if (chatError) throw chatError
    const chatId = chatData.id
    console.log("Chat ID created:", chatId)

    // 2. Process Pages (Embed & Save to 'documents')
    console.log(`Step 2: Processing ${pages.length} pages...`)
    
    let successCount = 0

    for (const page of pages) {
      const embedding = await generateEmbedding(page.content)
      //console.log("embeddigns : ",embedding);
      
      // 3. Insert into 'documents' (The Vector Table)
      const { error: docError } = await supabase
        .from('documents') // <--- Your Table Name
        .insert({
          user_id: userId,
          chat_id: chatId, // Link to the specific chat
          content: page.content,
          metadata: { pageNumber: page.page }, // Store page info in JSON
          embedding: embedding
        })

      if (docError) {
        console.error("Error saving document chunk:", docError)
      } else {
        successCount++
      }
    }

    console.log(`Finished! Saved ${successCount}/${pages.length} chunks.`)
    return chatId // Return the Chat ID so we can redirect the user there

  } catch (error) {
    console.error("Error in saveDocument:", error)
    throw error
  }
}